### ISSUE TITLE
Very slow shape extraction

### ISSUE THREAD

**Issue by petermr** [ContentMine/tilburg#1]
10_1186_s13643-015-0004-8 is very slow on one line which has a path with:
```
M188.453 298.19 L188.559 297.996 L188.666 297.81 L188.778 297.616 L188.884 297.429 L188.99 297.234 L; 33556
```
i.e. probably 2000 sublines. I suspect the slowness is quadratic parsing of strings and should
ue a StringBuilder (but this is a pure guess)

It's actually a dotted line drawn as
```
  <path
     fill="none"
     clip-path="url(#clipPath7)"
     stroke="#000000"
     stroke-dasharray="0 1"
     stroke-width="0.46900001"
```

**Comment by ghost** [comment]
Based on http://discuss.contentmine.org/t/extracting-data-from-tilburg-funnel-plot-diagrams/386/7 , which suggests that the code corresponding to this issue resides in the `svg` module, this issue should presumably be closed here and re-opened at https://github.com/ContentMine/svg/issues . OK to do that?

**Comment by petermr** [comment]
Yes.
