### ISSUE TITLE
Local directory referenced in Open Notebook

### ISSUE THREAD

**Issue by ghost** [ContentMine/tilburg#3]
http://discuss.contentmine.org/t/extracting-data-from-tilburg-funnel-plot-diagrams/386/9 says:

> The test corpus for the software is in the norma system (`/Users/pm286/workspace/cmdev/norma/src/test/resources/org/xmlcml/norma/plot`).

This reference to a local directory on a specific developer's PC seems to breach the 'no insider information' principle of [open notebook science](https://en.wikipedia.org/wiki/Open_notebook_science).

Instead of a local directory, please can this be amended to a world-accessible URL, so that others can access the same test corpus?

**Comment by petermr** [comment]
Added text

**Comment by ghost** [comment]
Thanks :)

There is a typo (the dir would be `.../src/src/...`), but this is still a big improvement.
